import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
const directory = dirname(fileURLToPath(import.meta.url));
const root = resolve(directory, '..');
const guide = JSON.parse(await readFile(resolve(directory, 'guide.json'), 'utf8'));
for (const section of guide.milestones) {
  section.files = await Promise.all(section.files.map(async ({ path, start, end }) => {
    const after = await readFile(resolve(root, path), 'utf8');
    const from = start ? after.indexOf(start) : 0;
    if (from < 0) throw new Error(`Excerpt start missing: ${path}: ${start}`);
    const to = end ? after.indexOf(end, from + 1) : after.length;
    if (to < 0) throw new Error(`Excerpt end missing: ${path}: ${end}`);
    return { path, after, diff: after.slice(from, to).trim(), deleted: false };
  }));
}
await writeFile(resolve(directory, 'presenter-data.js'),
  '// Generated by presenter/build.mjs from guide.json and this checkout.\nwindow.workshopPresenter = ' +
  JSON.stringify(guide, null, 2).replaceAll('<', '\\u003c') + ';\n');
